
#################################################################################################
# RECEPTOR-LIGAND ANALYSIS
#################################################################################################

## Returns full RL matrix given a RL table and a cutoff
```{r}
RLMatrix <- function(srt.data, rl, cutoff = .5) {
    num.cells <- ncol(srt.data)
    ans <- matrix(0, nrow = num.cells, ncol = num.cells)
    rl <- rl[(as.character(rl$Ligand) %in% rownames(srt.data)) & (as.character(rl$Receptor) %in% rownames(srt.data)),]
    rl <- rl[rowSums(as.matrix(srt.data[as.character(rl$Ligand),])>cutoff) > 0 & rowSums(as.matrix(srt.data[as.character(rl$Receptor),])>cutoff) > 0 , ]

    ligand.active <- srt.data[as.character(rl$Ligand),] > cutoff
    receptor.active <- srt.data[as.character(rl$Receptor),] > cutoff

    ans <- t(ligand.active) %*% receptor.active
    rownames(ans) <- colnames(ans) <- colnames(srt.data)
    ans
}
```

## Plots RL interaction network colored by cluster
```{r}
RLPlot <- function(rl.mat, srt, rl.cutoff = 5) {
  num.clusters <- length(unique(srt@ident))
  gg <- graph_from_adjacency_matrix(rl.mat > rl.cutoff, mode="undirected", weighted=T, diag=F, add.colnames=NA)
  V(gg)$size <- 2
  V(gg)$label <- NA
  V(gg)$color <- scales::hue_pal()(num.clusters)[srt@ident]
  gg <- delete.vertices(gg, which(degree(gg) == 0))
  plot(gg, layout = layout.fruchterman.reingold)
}
```

## Finds average interactions between pairs of clusters
```{r}
RLClust <- function(rl, srt) {
  num.clust <- length(unique(srt@ident))
  ans <- matrix(NA, nrow = num.clust, ncol = num.clust)

  for(i in 1:num.clust) {
    for(j in 1:num.clust) {
      ans[i,j] <- sum(rl[srt@ident==i, srt@ident == j])/(sum(srt@ident == i)*sum(srt@ident == j))
    }
  }

  ans
}
```

## Returns a sorted list of RL interactions for two clusters
```{r}
RLList <- function(srt, rl, ca, cb, cutoff = .5, de.only = T){
  # Filters only RLs in dataset
   rl <- rl[(as.character(rl$Ligand) %in% rownames(srt@data)) & (as.character(rl$Receptor) %in% rownames(srt@data)),]
   
   # Filters only RLs in DE list if requested
   if(de.only) {
     genes.lig <- unique(srt@cluster.markers$gene[srt@cluster.markers$cluster == ca])
     genes.rec <- unique(srt@cluster.markers$gene[srt@cluster.markers$cluster == cb])
     rl <- rl[(as.character(rl$Ligand) %in% genes.lig) & (as.character(rl$Receptor) %in% genes.rec),]
   }
   
    if(nrow(rl) > 1) {
      rl <- rl[rowSums(as.matrix(srt@data[as.character(rl$Ligand),])>cutoff) > 0 & rowSums(as.matrix(srt@data[as.character(rl$Receptor),])>cutoff) > 0 , ]
  
      ligands <- rowSums(as.matrix(srt@data[rl$Ligand, srt@ident == ca]) > cutoff)
      receptors <- rowSums(as.matrix(srt@data[rl$Receptor, srt@ident == cb]) > cutoff)
  
      ans <- (ligands * receptors)/((sum(srt@ident == ca))*(sum(srt@ident == cb)))
      names(ans) <- rownames(rl)
      ans <- ans[order(-ans)]
      ans <- ans[ans>0]
        
      return(ans)
    }

    return(NULL)
}

```
